Reservas Internacionales Netas - SERIES MENSUALES Millones de USD$

In [ ]:
import requests
import pandas as pd
from Clave import APIKEY

indicadoresIDs=[524]

FechaInicio="2020-1-01T00:00:00"
#FechaFinal="2019-12-01T00:00:00"
print(FechaInicio)
df_combinado=[]

for indicadorID in indicadoresIDs:
    urlCifras= f"https://bchapi-am.azure-api.net/api/v1/indicadores/{indicadorID}/cifras"
    urlIndicadores= f"https://bchapi-am.azure-api.net/api/v1/indicadores/{indicadorID}"
    
    params1={
        "fechainicio":FechaInicio
        #,"fechafinal":FechaFinal
    }
    
    headers = {
        "clave" : APIKEY,
        "Conten-Type": "application/json",
    }
    
    responseCifras = requests.get(urlCifras, headers=headers, params=params1)
    responseIndicadores = requests.get(urlIndicadores, headers=headers)
            
    if responseIndicadores.status_code == 200:
        datosIndicadores = responseIndicadores.json()
        #print(json.dumps(datosIndicadores,indent=4))  
        df_Indicadores=pd.DataFrame([datosIndicadores])
        ##print(df_Indicadores.to_string(index=False))
    else:
        print(f"Error {responseIndicadores.status_code}: {responseIndicadores.text}")
    
    if responseCifras.status_code == 200:
        datos1 = responseCifras.json()
        if datos1:
            df_Cifras=pd.DataFrame(datos1)
        else:
            df_Cifras=pd.DataFrame([{
            "Fecha":FechaInicio,
            "Id":0,       
            "IndicadorId":indicadorID,
            "Nombre":df_Indicadores.loc[0,"Nombre"],
            "Descripcion":df_Indicadores.loc[0,"Descripcion"],
            "Valor":0
            }])            
            ##print(df_Cifras.to_string(index=False))
            # Hacer negativo el valor si Indicador_ID es 113 o 155        
        #df_Cifras.loc[
        #    df_Cifras['IndicadorId'].isin([113, 155]), 'Valor'] = -df_Cifras.loc[df_Cifras['IndicadorId'].isin([113, 155]), 'Valor'
        #].abs()
    else:
        print(f"Error {responseCifras.status_code}: {responseCifras.text}")
  

    df_merge=pd.merge(
        df_Cifras,
        df_Indicadores,
        left_on='IndicadorId',
        right_on='Id',
        how='left'
    )

    #print(df_merge)
    #df_merge['Nombre_Indicador']= 'Indice de Precios al Consumidor IPC'  
    df_merge['NOMBRE_INDICADOR']=df_merge['Descripcion_x'].str.split('-').str[-2]
    df_merge['TIPO']=df_merge['Descripcion_x'].apply(lambda x:'-'.join(x.split('-')[3:5]))
    print(indicadorID, end=",")
    df_final=df_merge[['Fecha','IndicadorId','Periodicidad','Descripcion_x','Valor','NOMBRE_INDICADOR','TIPO']]
    df_combinado.append(df_final)
else:
    print(f"Error {responseCifras.status_code}: {responseCifras.text}") 

df_resultado=pd.concat(df_combinado, ignore_index=True)
df_resultado=df_resultado.rename(columns={
    'Fecha':'FECHA',
    'IndicadorId':'INDICADOR_ID',
    'Periodicidad':'PERIODICIDAD',
    'Descripcion_x':'DESCRIPCION',
    'Valor':'VALOR'
})
##df_merge.to_csv('indicador.csv', index=False, encoding='utf-8-sig')

2020-1-01T00:00:00
524,Error 200: [{"Id":2494501,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2025-04-01T00:00:00","Valor":8674.4000},{"Id":2321007,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2025-03-01T00:00:00","Valor":8403.5000},{"Id":2321006,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2025-02-01T00:00:00","Valor":8304.4000},{"Id":2018206,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2025-01-01T00:00:00","Valor":7962.5473},{"Id":2018205,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2024-12-01T00:00:00","Valor":8049.2016},{"Id":1674725,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2024-11-01T00:00:00","Valor":7381.1000},{"Id":1674724,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2024-10-01T00:00:00","Valor":6734.4000},{"Id":1264442,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2024-09-01T00:00:00","Valor":6767.0000},{"Id":1225312,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2024-08-01T00:00:00","Valor":6956.0000},{"Id":1225311,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2024-07-01T00:00:00","Valor":6932.2000},{"Id":1225310,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2024-06-01T00:00:00","Valor":6963.7000},{"Id":649049,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2024-05-01T00:00:00","Valor":7095.8000},{"Id":454271,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2024-04-01T00:00:00","Valor":7187.7000},{"Id":298824,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2024-03-01T00:00:00","Valor":7144.6000},{"Id":298823,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2024-02-01T00:00:00","Valor":7334.0000},{"Id":61798,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2024-01-01T00:00:00","Valor":7396.4000},{"Id":60287,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2024-01-01T00:00:00","Valor":7396.4000},{"Id":60285,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2023-12-01T00:00:00","Valor":7555.9000},{"Id":61796,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2023-12-01T00:00:00","Valor":7555.9000},{"Id":61794,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2023-11-01T00:00:00","Valor":7544.7000},{"Id":60283,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2023-11-01T00:00:00","Valor":7544.7000},{"Id":60281,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2023-10-01T00:00:00","Valor":7643.4000},{"Id":61792,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2023-10-01T00:00:00","Valor":7643.4000},{"Id":61790,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2023-09-01T00:00:00","Valor":7687.1000},{"Id":60279,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2023-09-01T00:00:00","Valor":7687.1000},{"Id":60277,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2023-08-01T00:00:00","Valor":7707.0000},{"Id":61788,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2023-08-01T00:00:00","Valor":7707.0000},{"Id":61786,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2023-07-01T00:00:00","Valor":7798.9000},{"Id":60276,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2023-07-01T00:00:00","Valor":7798.9000},{"Id":60274,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2023-06-01T00:00:00","Valor":7913.8000},{"Id":61784,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2023-06-01T00:00:00","Valor":7913.8000},{"Id":61782,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2023-05-01T00:00:00","Valor":8018.5000},{"Id":60272,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2023-05-01T00:00:00","Valor":8018.5000},{"Id":60270,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2023-04-01T00:00:00","Valor":8059.4000},{"Id":61780,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2023-04-01T00:00:00","Valor":8059.4000},{"Id":61778,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2023-03-01T00:00:00","Valor":8133.7000},{"Id":60268,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2023-03-01T00:00:00","Valor":8133.7000},{"Id":60266,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2023-02-01T00:00:00","Valor":8286.5000},{"Id":61776,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2023-02-01T00:00:00","Valor":8286.5000},{"Id":61774,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2023-01-01T00:00:00","Valor":8340.3000},{"Id":60264,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2023-01-01T00:00:00","Valor":8340.3000},{"Id":60262,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2022-12-01T00:00:00","Valor":8421.5000},{"Id":61772,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2022-12-01T00:00:00","Valor":8421.5000},{"Id":61770,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2022-11-01T00:00:00","Valor":8072.6000},{"Id":60260,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2022-11-01T00:00:00","Valor":8072.6000},{"Id":60258,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2022-10-01T00:00:00","Valor":8191.7000},{"Id":61768,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2022-10-01T00:00:00","Valor":8191.7000},{"Id":61766,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2022-09-01T00:00:00","Valor":8209.3000},{"Id":60256,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2022-09-01T00:00:00","Valor":8209.3000},{"Id":60254,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2022-08-01T00:00:00","Valor":8330.5000},{"Id":61764,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2022-08-01T00:00:00","Valor":8330.5000},{"Id":61762,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2022-07-01T00:00:00","Valor":8377.7000},{"Id":60252,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2022-07-01T00:00:00","Valor":8377.7000},{"Id":60250,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2022-06-01T00:00:00","Valor":8352.5000},{"Id":61760,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2022-06-01T00:00:00","Valor":8352.5000},{"Id":61758,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2022-05-01T00:00:00","Valor":8460.0000},{"Id":60248,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2022-05-01T00:00:00","Valor":8460.0000},{"Id":60246,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2022-04-01T00:00:00","Valor":8524.3000},{"Id":61756,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2022-04-01T00:00:00","Valor":8524.3000},{"Id":61754,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2022-03-01T00:00:00","Valor":8542.8000},{"Id":60244,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2022-03-01T00:00:00","Valor":8542.8000},{"Id":60242,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2022-02-01T00:00:00","Valor":8483.3000},{"Id":61752,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2022-02-01T00:00:00","Valor":8483.3000},{"Id":61750,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2022-01-01T00:00:00","Valor":8530.9000},{"Id":60240,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2022-01-01T00:00:00","Valor":8530.9000},{"Id":60238,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2021-12-01T00:00:00","Valor":8677.5568},{"Id":61748,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2021-12-01T00:00:00","Valor":8677.5568},{"Id":61746,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2021-11-01T00:00:00","Valor":8836.5576},{"Id":60236,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2021-11-01T00:00:00","Valor":8836.5576},{"Id":60234,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2021-10-01T00:00:00","Valor":8823.3399},{"Id":61743,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2021-10-01T00:00:00","Valor":8823.3399},{"Id":61741,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2021-09-01T00:00:00","Valor":8972.9109},{"Id":60232,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2021-09-01T00:00:00","Valor":8972.9109},{"Id":60230,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2021-08-01T00:00:00","Valor":8934.1515},{"Id":61739,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2021-08-01T00:00:00","Valor":8934.1515},{"Id":61737,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2021-07-01T00:00:00","Valor":8632.7698},{"Id":60228,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2021-07-01T00:00:00","Valor":8632.7698},{"Id":60226,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2021-06-01T00:00:00","Valor":8645.3845},{"Id":61735,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2021-06-01T00:00:00","Valor":8645.3845},{"Id":61733,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2021-05-01T00:00:00","Valor":8553.0882},{"Id":60224,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2021-05-01T00:00:00","Valor":8553.0882},{"Id":60222,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2021-04-01T00:00:00","Valor":8482.9649},{"Id":61731,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2021-04-01T00:00:00","Valor":8482.9649},{"Id":60220,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2021-03-01T00:00:00","Valor":8252.9434},{"Id":61729,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2021-03-01T00:00:00","Valor":8252.9434},{"Id":61727,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2021-02-01T00:00:00","Valor":8242.7006},{"Id":60218,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2021-02-01T00:00:00","Valor":8242.7006},{"Id":60216,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2021-01-01T00:00:00","Valor":8130.6444},{"Id":61725,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2021-01-01T00:00:00","Valor":8130.6444},{"Id":61723,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2020-12-01T00:00:00","Valor":8148.8198},{"Id":60214,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2020-12-01T00:00:00","Valor":8148.8198},{"Id":60212,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2020-11-01T00:00:00","Valor":8195.0071},{"Id":61721,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2020-11-01T00:00:00","Valor":8195.0071},{"Id":61719,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2020-10-01T00:00:00","Valor":7760.3984},{"Id":60210,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2020-10-01T00:00:00","Valor":7760.3984},{"Id":60208,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2020-09-01T00:00:00","Valor":7519.8231},{"Id":61717,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2020-09-01T00:00:00","Valor":7519.8231},{"Id":61715,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2020-08-01T00:00:00","Valor":7510.3814},{"Id":60206,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2020-08-01T00:00:00","Valor":7510.3814},{"Id":60204,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2020-07-01T00:00:00","Valor":7513.6555},{"Id":61713,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2020-07-01T00:00:00","Valor":7513.6555},{"Id":61711,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2020-06-01T00:00:00","Valor":7388.9930},{"Id":60202,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2020-06-01T00:00:00","Valor":7388.9930},{"Id":60200,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2020-05-01T00:00:00","Valor":6353.3315},{"Id":61709,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2020-05-01T00:00:00","Valor":6353.3315},{"Id":61707,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2020-04-01T00:00:00","Valor":6131.0468},{"Id":60198,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2020-04-01T00:00:00","Valor":6131.0468},{"Id":60197,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2020-03-01T00:00:00","Valor":6086.2314},{"Id":61705,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2020-03-01T00:00:00","Valor":6086.2314},{"Id":61703,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2020-02-01T00:00:00","Valor":5855.4886},{"Id":60195,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2020-02-01T00:00:00","Valor":5855.4886},{"Id":60193,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2020-01-01T00:00:00","Valor":5763.9582},{"Id":61701,"IndicadorId":524,"Nombre":"EM-RIN-01-1","Descripcion":"EM-RIN-01 - Reservas Internacionales Netas - Saldo","Fecha":"2020-01-01T00:00:00","Valor":5763.9582}]

In [29]:
df_resultado.head(10)

,FECHA,INDICADOR_ID,PERIODICIDAD,DESCRIPCION,VALOR,NOMBRE_INDICADOR,TIPO
0,2025-04-01T00:00:00,524,Mensual,EM-RIN-01 - Reservas Internacionales Netas - S...,8674.4000,Reservas Internacionales Netas,Reservas Internacionales Netas - Saldo
1,2025-03-01T00:00:00,524,Mensual,EM-RIN-01 - Reservas Internacionales Netas - S...,8403.5000,Reservas Internacionales Netas,Reservas Internacionales Netas - Saldo
2,2025-02-01T00:00:00,524,Mensual,EM-RIN-01 - Reservas Internacionales Netas - S...,8304.4000,Reservas Internacionales Netas,Reservas Internacionales Netas - Saldo
3,2025-01-01T00:00:00,524,Mensual,EM-RIN-01 - Reservas Internacionales Netas - S...,7962.5473,Reservas Internacionales Netas,Reservas Internacionales Netas - Saldo
4,2024-12-01T00:00:00,524,Mensual,EM-RIN-01 - Reservas Internacionales Netas - S...,8049.2016,Reservas Internacionales Netas,Reservas Internacionales Netas - Saldo
5,2024-11-01T00:00:00,524,Mensual,EM-RIN-01 - Reservas Internacionales Netas - S...,7381.1000,Reservas Internacionales Netas,Reservas Internacionales Netas - Saldo
6,2024-10-01T00:00:00,524,Mensual,EM-RIN-01 - Reservas Internacionales Netas - S...,6734.4000,Reservas Internacionales Netas,Reservas Internacionales Netas - Saldo
7,2024-09-01T00:00:00,524,Mensual,EM-RIN-01 - Reservas Internacionales Netas - S...,6767.0000,Reservas Internacionales Netas,Reservas Internacionales Netas - Saldo
8,2024-08-01T00:00:00,524,Mensual,EM-RIN-01 - Reservas Internacionales Netas - S...,6956.0000,Reservas Internacionales Netas,Reservas Internacionales Netas - Saldo
9,2024-07-01T00:00:00,524,Mensual,EM-RIN-01 - Reservas Internacionales Netas - S...,6932.2000,Reservas Internacionales Netas,Reservas Internacionales Netas - Saldo

In [30]:
#df_resultado.drop_duplicates().shape
#df_resultado['TIPO'] = df_resultado['TIPO'].str.strip()
df_resultado['TIPO'] = 'Reservas Monetarias Internacionales'
df_resultado['NOMBRE_INDICADOR'] = df_resultado['NOMBRE_INDICADOR'].str.strip()
df_resultado=df_resultado.drop_duplicates()
df_resultado.head(10)

,FECHA,INDICADOR_ID,PERIODICIDAD,DESCRIPCION,VALOR,NOMBRE_INDICADOR,TIPO
0,2025-04-01T00:00:00,524,Mensual,EM-RIN-01 - Reservas Internacionales Netas - S...,8674.4000,Reservas Internacionales Netas,Reservas Monetarias Internacionales
1,2025-03-01T00:00:00,524,Mensual,EM-RIN-01 - Reservas Internacionales Netas - S...,8403.5000,Reservas Internacionales Netas,Reservas Monetarias Internacionales
2,2025-02-01T00:00:00,524,Mensual,EM-RIN-01 - Reservas Internacionales Netas - S...,8304.4000,Reservas Internacionales Netas,Reservas Monetarias Internacionales
3,2025-01-01T00:00:00,524,Mensual,EM-RIN-01 - Reservas Internacionales Netas - S...,7962.5473,Reservas Internacionales Netas,Reservas Monetarias Internacionales
4,2024-12-01T00:00:00,524,Mensual,EM-RIN-01 - Reservas Internacionales Netas - S...,8049.2016,Reservas Internacionales Netas,Reservas Monetarias Internacionales
5,2024-11-01T00:00:00,524,Mensual,EM-RIN-01 - Reservas Internacionales Netas - S...,7381.1000,Reservas Internacionales Netas,Reservas Monetarias Internacionales
6,2024-10-01T00:00:00,524,Mensual,EM-RIN-01 - Reservas Internacionales Netas - S...,6734.4000,Reservas Internacionales Netas,Reservas Monetarias Internacionales
7,2024-09-01T00:00:00,524,Mensual,EM-RIN-01 - Reservas Internacionales Netas - S...,6767.0000,Reservas Internacionales Netas,Reservas Monetarias Internacionales
8,2024-08-01T00:00:00,524,Mensual,EM-RIN-01 - Reservas Internacionales Netas - S...,6956.0000,Reservas Internacionales Netas,Reservas Monetarias Internacionales
9,2024-07-01T00:00:00,524,Mensual,EM-RIN-01 - Reservas Internacionales Netas - S...,6932.2000,Reservas Internacionales Netas,Reservas Monetarias Internacionales

In [31]:
################           INSERT TABLE / DATA           #################   #      
from azure.identity import InteractiveBrowserCredential
import pandas as pd
from Server import AZURE
from tqdm import tqdm
from sqlalchemy import create_engine, text

credential = InteractiveBrowserCredential()

server = AZURE
database = 'sqlpooldwhandr01'
schema = 'HN_NAP_HO_MISRIESGOS_F'
tabla = 'INDICADORES_MACROECONOMICOS'
driver = "ODBC Driver 17 for SQL Server"

connection_string = (
        f"DRIVER={driver};"
        f"SERVER={server};"
        f"DATABASE={database};"
        f"Encrypt=yes;"
        f"TrustServerCertificate=no;"
        f"Authentication=ActiveDirectoryInteractive;"
    )

connection_uri = f"mssql+pyodbc:///?odbc_connect={connection_string}"
engine = create_engine(connection_uri, fast_executemany=True)


query = text("""
SELECT COLUMN_NAME, DATA_TYPE , CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = :tablita
AND TABLE_SCHEMA = :esquema
""")

with engine.connect() as conn:
    result = conn.execute(query, {"tablita": tabla, "esquema":schema})
    columns_types = {row[0]: [row[1] , row[2]] for row in result}
#columns_types

In [32]:
#-----------------------------############### INSERT ##################------------------------------------#
#tmp_df = df_cleaned.iloc[:100].copy()


#data_frame = pd.DataFrame(js)
df_resultado['FECHA']=pd.to_datetime(df_resultado['FECHA']).dt.strftime('%Y-%m-%d')
data_frame=df_resultado
chunksize = 100

for start in tqdm(range(0, len(data_frame), chunksize), desc="Insertando datos"):
    end = min(start + chunksize, len(data_frame))
    chunk = data_frame.iloc[start:end]

    try:
        chunk.to_sql(tabla, 
                     con=engine, 
                     schema=schema, 
                     if_exists='append', 
                     index=False, 
                     chunksize=chunksize)
    except Exception as e:
        print(f"Error al insertar datos en la base de datos: {e}")
    #break
print('Proceso de insercion completado')

Insertando datos: 100%|██████████| 1/1 [00:09<00:00,  9.40s/it]

Proceso de insercion completado