Tasa Politica Monetaria TPM (BCH)

In [18]:
import requests
import pandas as pd
from Clave import APIKEY
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)


indicadoresIDs=[700]
FechaInicio="2015-01-01T00:00:00"
#FechaFinal="2019-12-01T00:00:00"
print(FechaInicio)
df_combinado=[]

for indicadorID in indicadoresIDs:
    urlCifras= f"https://bchapi-am.azure-api.net/api/v1/indicadores/{indicadorID}/cifras"
    urlIndicadores= f"https://bchapi-am.azure-api.net/api/v1/indicadores/{indicadorID}"
    
    params1={
        "fechainicio":FechaInicio
        #,"fechafinal":FechaFinal
    }
    
    headers = {
        "clave" : APIKEY,
        "Conten-Type": "application/json",
    }
    
    responseCifras = requests.get(urlCifras, headers=headers, params=params1, verify=False)
    responseIndicadores = requests.get(urlIndicadores, headers=headers,verify=False)
            
    if responseIndicadores.status_code == 200:
        datosIndicadores = responseIndicadores.json()
        #print(json.dumps(datosIndicadores,indent=4))  
        df_Indicadores=pd.DataFrame([datosIndicadores])
        ##print(df_Indicadores.to_string(index=False))
    else:
        print(f"Error {responseIndicadores.status_code}: {responseIndicadores.text}")
    
    if responseCifras.status_code == 200:
        datos1 = responseCifras.json()
        if datos1:
            df_Cifras=pd.DataFrame(datos1)
        else:
            df_Cifras=pd.DataFrame([{
            "Fecha":FechaInicio,
            "Id":0,       
            "IndicadorId":indicadorID,
            "Nombre":df_Indicadores.loc[0,"Nombre"],
            "Descripcion":df_Indicadores.loc[0,"Descripcion"],
            "Valor":0
            }])            
            ##print(df_Cifras.to_string(index=False))
            # Hacer negativo el valor si Indicador_ID es 113 o 155        
        #df_Cifras.loc[
        #    df_Cifras['IndicadorId'].isin([113, 155]), 'Valor'] = -df_Cifras.loc[df_Cifras['IndicadorId'].isin([113, 155]), 'Valor'
        #].abs()
    else:
        print(f"Error {responseCifras.status_code}: {responseCifras.text}")
  

    df_merge=pd.merge(
        df_Cifras,
        df_Indicadores,
        left_on='IndicadorId',
        right_on='Id',
        how='left'
    )

    #print(df_merge)
    #df_merge['Nombre_Indicador']= 'Indice de Precios al Consumidor IPC'  
    df_merge['NOMBRE_INDICADOR']=df_merge['Descripcion_x'].str.split('-').str[-2]
    df_merge['TIPO']=df_merge['Descripcion_x'].apply(lambda x:'-'.join(x.split('-')[3:5]))
    print(indicadorID, end=",")
    df_final=df_merge[['Fecha','IndicadorId','Periodicidad','Descripcion_x','Valor','NOMBRE_INDICADOR','TIPO']]
    df_combinado.append(df_final)
else:
    print(f"Error {responseCifras.status_code}: {responseCifras.text}") 

df_resultado=pd.concat(df_combinado, ignore_index=True)
df_resultado=df_resultado.rename(columns={
    'Fecha':'FECHA',
    'IndicadorId':'INDICADOR_ID',
    'Periodicidad':'PERIODICIDAD',
    'Descripcion_x':'DESCRIPCION',
    'Valor':'VALOR'
})
##df_merge.to_csv('indicador.csv', index=False, encoding='utf-8-sig')

2015-01-01T00:00:00
700,Error 200: [{"Id":2494628,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2025-05-30T00:00:00","Valor":0.0575},{"Id":2326863,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2025-04-30T00:00:00","Valor":0.0575},{"Id":2158962,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2025-03-31T00:00:00","Valor":0.0575},{"Id":2024037,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2025-02-28T00:00:00","Valor":0.0575},{"Id":2024036,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2025-01-31T00:00:00","Valor":0.0575},{"Id":1708168,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2024-12-31T00:00:00","Valor":0.0575},{"Id":1552503,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2024-11-30T00:00:00","Valor":0.0575},{"Id":1319960,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2024-10-31T00:00:00","Valor":0.0575},{"Id":1203155,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2024-09-30T00:00:00","Valor":0.0400},{"Id":1053509,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2024-08-31T00:00:00","Valor":0.0400},{"Id":837533,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2024-08-05T00:00:00","Valor":0.0400},{"Id":815397,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2024-07-31T00:00:00","Valor":0.0300},{"Id":704668,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2024-06-30T00:00:00","Valor":0.0300},{"Id":704667,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2024-05-31T00:00:00","Valor":0.0300},{"Id":704666,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2024-04-30T00:00:00","Valor":0.0300},{"Id":704665,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2024-03-31T00:00:00","Valor":0.0300},{"Id":704664,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2024-02-29T00:00:00","Valor":0.0300},{"Id":124884,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2024-01-31T00:00:00","Valor":0.0300},{"Id":124883,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2023-12-31T00:00:00","Valor":0.0300},{"Id":124882,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2023-11-30T00:00:00","Valor":0.0300},{"Id":124881,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2023-10-31T00:00:00","Valor":0.0300},{"Id":124880,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2023-09-30T00:00:00","Valor":0.0300},{"Id":124879,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2023-08-31T00:00:00","Valor":0.0300},{"Id":124878,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2023-07-31T00:00:00","Valor":0.0300},{"Id":124877,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2023-06-30T00:00:00","Valor":0.0300},{"Id":124876,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2023-05-31T00:00:00","Valor":0.0300},{"Id":124875,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2023-04-30T00:00:00","Valor":0.0300},{"Id":124874,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2023-03-31T00:00:00","Valor":0.0300},{"Id":124873,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2023-02-28T00:00:00","Valor":0.0300},{"Id":124872,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2023-01-31T00:00:00","Valor":0.0300},{"Id":124871,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2022-12-31T00:00:00","Valor":0.0300},{"Id":124870,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2022-11-30T00:00:00","Valor":0.0300},{"Id":124869,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2022-10-31T00:00:00","Valor":0.0300},{"Id":124868,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2022-09-30T00:00:00","Valor":0.0300},{"Id":124867,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2022-08-31T00:00:00","Valor":0.0300},{"Id":124866,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2022-07-31T00:00:00","Valor":0.0300},{"Id":124865,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2022-06-30T00:00:00","Valor":0.0300},{"Id":124864,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2022-05-31T00:00:00","Valor":0.0300},{"Id":124863,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2022-04-30T00:00:00","Valor":0.0300},{"Id":124862,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2022-03-31T00:00:00","Valor":0.0300},{"Id":124861,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2022-02-28T00:00:00","Valor":0.0300},{"Id":124860,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2022-01-31T00:00:00","Valor":0.0300},{"Id":124859,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2021-12-31T00:00:00","Valor":0.0300},{"Id":124858,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2021-11-30T00:00:00","Valor":0.0300},{"Id":124857,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2021-10-31T00:00:00","Valor":0.0300},{"Id":124856,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2021-09-30T00:00:00","Valor":0.0300},{"Id":124855,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2021-08-31T00:00:00","Valor":0.0300},{"Id":124854,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2021-07-31T00:00:00","Valor":0.0300},{"Id":124853,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2021-06-30T00:00:00","Valor":0.0300},{"Id":124852,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2021-05-31T00:00:00","Valor":0.0300},{"Id":124851,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2021-04-30T00:00:00","Valor":0.0300},{"Id":124850,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2021-03-31T00:00:00","Valor":0.0300},{"Id":124849,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2021-02-28T00:00:00","Valor":0.0300},{"Id":124848,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2021-01-31T00:00:00","Valor":0.0300},{"Id":124847,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2020-12-31T00:00:00","Valor":0.0300},{"Id":124846,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2020-11-30T00:00:00","Valor":0.0300},{"Id":124845,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2020-10-31T00:00:00","Valor":0.0375},{"Id":124844,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2020-09-30T00:00:00","Valor":0.0375},{"Id":124843,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2020-08-31T00:00:00","Valor":0.0375},{"Id":124842,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2020-07-31T00:00:00","Valor":0.0450},{"Id":124841,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2020-06-30T00:00:00","Valor":0.0450},{"Id":124840,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2020-05-31T00:00:00","Valor":0.0450},{"Id":124839,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2020-04-30T00:00:00","Valor":0.0450},{"Id":124838,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2020-03-31T00:00:00","Valor":0.0450},{"Id":124837,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2020-02-29T00:00:00","Valor":0.0525},{"Id":124836,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2020-01-31T00:00:00","Valor":0.0550},{"Id":124835,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2019-12-31T00:00:00","Valor":0.0550},{"Id":124834,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2019-11-30T00:00:00","Valor":0.0575},{"Id":124833,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2019-10-31T00:00:00","Valor":0.0575},{"Id":124832,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2019-09-30T00:00:00","Valor":0.0575},{"Id":124831,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2019-08-31T00:00:00","Valor":0.0575},{"Id":124830,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2019-07-31T00:00:00","Valor":0.0575},{"Id":124829,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2019-06-30T00:00:00","Valor":0.0575},{"Id":124828,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2019-05-31T00:00:00","Valor":0.0575},{"Id":124827,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2019-04-30T00:00:00","Valor":0.0575},{"Id":124826,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2019-03-31T00:00:00","Valor":0.0575},{"Id":124825,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2019-02-28T00:00:00","Valor":0.0575},{"Id":124824,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2019-01-31T00:00:00","Valor":0.0575},{"Id":124823,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2018-12-31T00:00:00","Valor":0.0550},{"Id":124822,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2018-11-30T00:00:00","Valor":0.0550},{"Id":124821,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2018-10-31T00:00:00","Valor":0.0550},{"Id":124820,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2018-09-30T00:00:00","Valor":0.0550},{"Id":124819,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2018-08-31T00:00:00","Valor":0.0550},{"Id":124818,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2018-07-31T00:00:00","Valor":0.0550},{"Id":124817,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2018-06-30T00:00:00","Valor":0.0550},{"Id":124816,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2018-05-31T00:00:00","Valor":0.0550},{"Id":124815,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2018-04-30T00:00:00","Valor":0.0550},{"Id":124814,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2018-03-31T00:00:00","Valor":0.0550},{"Id":124813,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2018-02-28T00:00:00","Valor":0.0550},{"Id":124812,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2018-01-31T00:00:00","Valor":0.0550},{"Id":124811,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2017-12-31T00:00:00","Valor":0.0550},{"Id":124810,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2017-11-30T00:00:00","Valor":0.0550},{"Id":124809,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2017-10-31T00:00:00","Valor":0.0550},{"Id":124808,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2017-09-30T00:00:00","Valor":0.0550},{"Id":124807,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2017-08-31T00:00:00","Valor":0.0550},{"Id":124806,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2017-07-31T00:00:00","Valor":0.0550},{"Id":124805,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2017-06-30T00:00:00","Valor":0.0550},{"Id":124804,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2017-05-31T00:00:00","Valor":0.0550},{"Id":124803,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2017-04-30T00:00:00","Valor":0.0550},{"Id":124802,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2017-03-31T00:00:00","Valor":0.0550},{"Id":124801,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2017-02-28T00:00:00","Valor":0.0550},{"Id":124800,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2017-01-31T00:00:00","Valor":0.0550},{"Id":124799,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2016-12-31T00:00:00","Valor":0.0550},{"Id":124798,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2016-11-30T00:00:00","Valor":0.0550},{"Id":124797,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2016-10-31T00:00:00","Valor":0.0550},{"Id":124796,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2016-09-30T00:00:00","Valor":0.0550},{"Id":124795,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2016-08-31T00:00:00","Valor":0.0550},{"Id":124794,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2016-07-31T00:00:00","Valor":0.0550},{"Id":124793,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2016-06-30T00:00:00","Valor":0.0550},{"Id":124792,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2016-05-31T00:00:00","Valor":0.0575},{"Id":124791,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2016-04-30T00:00:00","Valor":0.0575},{"Id":124790,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2016-03-31T00:00:00","Valor":0.0575},{"Id":124789,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2016-02-29T00:00:00","Valor":0.0625},{"Id":124788,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2016-01-31T00:00:00","Valor":0.0625},{"Id":124787,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2015-12-31T00:00:00","Valor":0.0625},{"Id":124786,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2015-11-30T00:00:00","Valor":0.0625},{"Id":124785,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2015-10-31T00:00:00","Valor":0.0625},{"Id":124784,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2015-09-30T00:00:00","Valor":0.0625},{"Id":124783,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2015-08-31T00:00:00","Valor":0.0625},{"Id":124782,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2015-07-31T00:00:00","Valor":0.0625},{"Id":124781,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2015-06-30T00:00:00","Valor":0.0650},{"Id":124780,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2015-05-31T00:00:00","Valor":0.0650},{"Id":124779,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2015-04-30T00:00:00","Valor":0.0650},{"Id":124778,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2015-03-31T00:00:00","Valor":0.0650},{"Id":124777,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2015-02-28T00:00:00","Valor":0.0675},{"Id":124776,"IndicadorId":700,"Nombre":"EM-TPM-01-2","Descripcion":"Tasa Politica Monetaria - Mensual","Fecha":"2015-01-31T00:00:00","Valor":0.0700}]

In [21]:
df_resultado.head(10)

,FECHA,INDICADOR_ID,PERIODICIDAD,DESCRIPCION,VALOR,NOMBRE_INDICADOR,TIPO
0,2025-05-30T00:00:00,700,Mensual,Tasa Politica Monetaria - Mensual,0.0575,Tasa Politica Monetaria,Tasa Politica Monetaria
1,2025-04-30T00:00:00,700,Mensual,Tasa Politica Monetaria - Mensual,0.0575,Tasa Politica Monetaria,Tasa Politica Monetaria
2,2025-03-31T00:00:00,700,Mensual,Tasa Politica Monetaria - Mensual,0.0575,Tasa Politica Monetaria,Tasa Politica Monetaria
3,2025-02-28T00:00:00,700,Mensual,Tasa Politica Monetaria - Mensual,0.0575,Tasa Politica Monetaria,Tasa Politica Monetaria
4,2025-01-31T00:00:00,700,Mensual,Tasa Politica Monetaria - Mensual,0.0575,Tasa Politica Monetaria,Tasa Politica Monetaria
5,2024-12-31T00:00:00,700,Mensual,Tasa Politica Monetaria - Mensual,0.0575,Tasa Politica Monetaria,Tasa Politica Monetaria
6,2024-11-30T00:00:00,700,Mensual,Tasa Politica Monetaria - Mensual,0.0575,Tasa Politica Monetaria,Tasa Politica Monetaria
7,2024-10-31T00:00:00,700,Mensual,Tasa Politica Monetaria - Mensual,0.0575,Tasa Politica Monetaria,Tasa Politica Monetaria
8,2024-09-30T00:00:00,700,Mensual,Tasa Politica Monetaria - Mensual,0.0400,Tasa Politica Monetaria,Tasa Politica Monetaria
9,2024-08-31T00:00:00,700,Mensual,Tasa Politica Monetaria - Mensual,0.0400,Tasa Politica Monetaria,Tasa Politica Monetaria

In [24]:
#df_resultado.drop_duplicates().shape
#df_resultado['TIPO'] = df_resultado['TIPO'].str.strip()
df_resultado['TIPO'] = 'Tasa Politica Monetaria'
df_resultado['VARIACION'] = 0
df_resultado['NOMBRE_INDICADOR'] = df_resultado['NOMBRE_INDICADOR'].str.strip()
df_resultado=df_resultado.drop_duplicates()
df_resultado.head(10)

,FECHA,INDICADOR_ID,PERIODICIDAD,DESCRIPCION,VALOR,NOMBRE_INDICADOR,TIPO,VARIACION
0,2025-05-30,700,Mensual,Tasa Politica Monetaria - Mensual,0.0575,Tasa Politica Monetaria,Tasa Politica Monetaria,0
1,2025-04-30,700,Mensual,Tasa Politica Monetaria - Mensual,0.0575,Tasa Politica Monetaria,Tasa Politica Monetaria,0
2,2025-03-31,700,Mensual,Tasa Politica Monetaria - Mensual,0.0575,Tasa Politica Monetaria,Tasa Politica Monetaria,0
3,2025-02-28,700,Mensual,Tasa Politica Monetaria - Mensual,0.0575,Tasa Politica Monetaria,Tasa Politica Monetaria,0
4,2025-01-31,700,Mensual,Tasa Politica Monetaria - Mensual,0.0575,Tasa Politica Monetaria,Tasa Politica Monetaria,0
5,2024-12-31,700,Mensual,Tasa Politica Monetaria - Mensual,0.0575,Tasa Politica Monetaria,Tasa Politica Monetaria,0
6,2024-11-30,700,Mensual,Tasa Politica Monetaria - Mensual,0.0575,Tasa Politica Monetaria,Tasa Politica Monetaria,0
7,2024-10-31,700,Mensual,Tasa Politica Monetaria - Mensual,0.0575,Tasa Politica Monetaria,Tasa Politica Monetaria,0
8,2024-09-30,700,Mensual,Tasa Politica Monetaria - Mensual,0.0400,Tasa Politica Monetaria,Tasa Politica Monetaria,0
9,2024-08-31,700,Mensual,Tasa Politica Monetaria - Mensual,0.0400,Tasa Politica Monetaria,Tasa Politica Monetaria,0

In [22]:
################           INSERT TABLE / DATA           #################   #      
from azure.identity import InteractiveBrowserCredential
import pandas as pd
from Server import AZURE
from tqdm import tqdm
from sqlalchemy import create_engine, text

credential = InteractiveBrowserCredential()

server = AZURE
database = 'sqlpooldwhandr01'
schema = 'HN_NAP_HO_MISRIESGOS_F'
tabla = 'INDICADORES_MACROECONOMICOS'
driver = "ODBC Driver 17 for SQL Server"

connection_string = (
        f"DRIVER={driver};"
        f"SERVER={server};"
        f"DATABASE={database};"
        f"Encrypt=yes;"
        f"TrustServerCertificate=no;"
        f"Authentication=ActiveDirectoryInteractive;"
    )

connection_uri = f"mssql+pyodbc:///?odbc_connect={connection_string}"
engine = create_engine(connection_uri, fast_executemany=True)


query = text("""
SELECT COLUMN_NAME, DATA_TYPE , CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = :tablita
AND TABLE_SCHEMA = :esquema
""")

with engine.connect() as conn:
    result = conn.execute(query, {"tablita": tabla, "esquema":schema})
    columns_types = {row[0]: [row[1] , row[2]] for row in result}
#columns_types

In [23]:
#-----------------------------############### INSERT ##################------------------------------------#
#tmp_df = df_cleaned.iloc[:100].copy()


#data_frame = pd.DataFrame(js)
df_resultado['FECHA']=pd.to_datetime(df_resultado['FECHA']).dt.strftime('%Y-%m-%d')
data_frame=df_resultado
chunksize = 100

for start in tqdm(range(0, len(data_frame), chunksize), desc="Insertando datos"):
    end = min(start + chunksize, len(data_frame))
    chunk = data_frame.iloc[start:end]

    try:
        chunk.to_sql(tabla, 
                     con=engine, 
                     schema=schema, 
                     if_exists='append', 
                     index=False, 
                     chunksize=chunksize)
    except Exception as e:
        print(f"Error al insertar datos en la base de datos: {e}")
    #break
print('Proceso de insercion completado')

Insertando datos: 100%|██████████| 2/2 [00:19<00:00,  9.89s/it]

Proceso de insercion completado